name: Deploy Hugo to FTP

# Trigger bei Push zum main Branch und manuell
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Hugo site
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.142.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '${{ env.HUGO_VERSION }}'
          extended: true

      - name: Build Hugo site
        run: hugo --minify --gc -b https://nicgeon.de

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: './public'
          retention-days: 1

  deploy:
    name: Deploy to SFTP
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: hugo-site
          path: './public'

      - name: Deploy to SFTP server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './public/*'
          remote_path: '/var/www/html/nicgeon.de/public_html/'
          sftp_only: true
          port: 2222
